#!/bin/bash
cd $(dirname $0)

rm -rf node_modules/@types/eslint-scope/ matrix-*-sdk/node_modules/@types/eslint-scope

cd matrix-js-sdk
git checkout . && git pull
jsver=$(git rev-parse origin/develop)
jsver=${jsver:0:12}
cd ..
git checkout yarn.lock
bash -c "git stash && git pull && git stash pop"
ver=$(git rev-parse origin/develop)
ver=${ver:0:12}

docker run --rm -w /data -it \
	-v $(pwd):/data \
	-v $(pwd)/.home:/home/tulir \
	-v /etc/passwd:/etc/passwd:ro \
	--env VERSION="$ver-js-$jsver" \
	node:lts-alpine \
	/bin/sh -c 'apk add --no-cache git su-exec && su-exec 1000:1000 /data/build-sh'

if [[ $? -eq 0 ]]; then
	sudo rsync --delete -tvhr webapp/ /srv/web/mau.chat/
fi
