#!/bin/sh
set -euo pipefail
rm -rf webapp/bundles/

#export CI_PACKAGE="this is a hacky way to enable debug builds"

echo "Updating matrix-js-sdk..."
cd packages/matrix-js-sdk
pnpm install
pnpm run build
cd ../..

echo "Updating element-web..."
cd apps/web
pnpm install
pnpm run build
cd ../..

echo "$VERSION" > webapp/version
cp -f config.*.json webapp/

echo "All done"
